# Setze Fenstertitel
$host.UI.RawUI.WindowTitle = "Spriz Studio"

# Setze Farben (Gelb auf Schwarz)
$Host.UI.RawUI.ForegroundColor = "Yellow"
$Host.UI.RawUI.BackgroundColor = "Black"
Clear-Host

# ASCII-Art als Here-String
$asciiArt = @"
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMddooo:::oosdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMy+:::---------:/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMmo----------:ohdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMd:---------/oNMMNmyysyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMd:--------+dNMMmy:-----:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMN/------:+dMMMN+----------:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMo-------sMMMNy:-------------omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMM------:yMMMm/-----------------hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMy-----/dMMMm/-------------------/NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMN/----:dMMMm:---------------------:yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMd----:yMMMN+------------------------+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMo----oMMMMh---------------------------yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMN:----mMMMM/----------------------------/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMy----+NMMMM:-----------------------------:yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMN:----yMMMMM+-------------------------------+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMN----:NMMMMMNo:------------------------------:hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMN----/MMMMMMMMmho/----------------------------:hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMs----yMMMMMm++++++o+:-///://///----------------/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMM+----dMMMMy:----------:::-::::o++++syyy+ssss/osmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMM+----dMMMd-----------------------------:///oydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMh----dMMM+------------------------------------dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMN----dMMM-------------------------------------soosdMMNhhhdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMN/---dMMM------------------------------------------dd/----:+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMy---+MMM-----------------------------------------:d:--------/yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMN/--:NMM-----------------------------------------o/-----------:sdMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMh---oMM/---------------------------:-----------:+---------------+dMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMN+---hMh----------------------://--------------/:-----------------+NMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMm---:hh-------------------:/+/:--------------::-------------------/yNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMy:--:h+--------------::o+/:----------------:+----------------------+NMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMy:--:y:---------:+sso+/-------------------o:-----------------------+dMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMy:--:s+::::++yddh+:---------------------++-------------------------:yNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMy:--:smmmmMMMs:------------------------s:---------------------------+NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMd+:-:+NMMMMh-------------------------ys-----------------------------yMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMy:--/yMMMNs-----------------------om------------------------------yMMMNmNNMMMMMMMMMM
MMMMMMMMMMMMMMMMd/--:oyNMMh/---------------------Mo-----------------------------sMMMd+-:oMMMMMMMMMM
MMMMMMMMMMMMMMMMMMh/---:ydMMh+:----------------:hd----------------------------/hNms+--:+mMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNho:---+hmNNdy+-------------hMs--------------------------/hNyo:--:+dMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNs+::-:/yhNNmho:::-----omMM------------------------:oyyo/--:/omMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMmyo/:---/+sdmNmddddmMMMMh/:------------------:/+o/---:/oymMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyo/::---/++symmmMMMMMmdys////::///-----::---:/oymMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhs+/::-----/////////////::///-----::+yymMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdhyooo/:::::::-------::::+oohNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhhhhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"@

# ASCII-Art anzeigen
Write-Host $asciiArt

$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
